// GENERATED by `mining-accidents build-dashboard` — do not edit.
// Contents mirror data/public/ (the reviewed public export) plus
// aggregate pipeline-status counts. See dashboard/README.md.
window.MINING_DATA = {
  "aggregates": [
    {
      "comparability_notes": "Sector-wide miner work deaths, all causes, per İSİG annual reports as transcribed by the Wikipedia list. NOT comparable to the per-incident register (which covers listed accidents only) and never a rate: no exposure denominator.",
      "deaths": 81,
      "institution": "İSİG Meclisi (via tr.wikipedia list article)",
      "year": 2012
    },
    {
      "comparability_notes": "Sector-wide miner work deaths, all causes, per İSİG annual reports as transcribed by the Wikipedia list. NOT comparable to the per-incident register (which covers listed accidents only) and never a rate: no exposure denominator.",
      "deaths": 93,
      "institution": "İSİG Meclisi (via tr.wikipedia list article)",
      "year": 2013
    },
    {
      "comparability_notes": "Sector-wide miner work deaths, all causes, per İSİG annual reports as transcribed by the Wikipedia list. NOT comparable to the per-incident register (which covers listed accidents only) and never a rate: no exposure denominator.",
      "deaths": 386,
      "institution": "İSİG Meclisi (via tr.wikipedia list article)",
      "year": 2014
    },
    {
      "comparability_notes": "Sector-wide miner work deaths, all causes, per İSİG annual reports as transcribed by the Wikipedia list. NOT comparable to the per-incident register (which covers listed accidents only) and never a rate: no exposure denominator.",
      "deaths": 67,
      "institution": "İSİG Meclisi (via tr.wikipedia list article)",
      "year": 2015
    },
    {
      "comparability_notes": "Sector-wide miner work deaths, all causes, per İSİG annual reports as transcribed by the Wikipedia list. NOT comparable to the per-incident register (which covers listed accidents only) and never a rate: no exposure denominator.",
      "deaths": 73,
      "institution": "İSİG Meclisi (via tr.wikipedia list article)",
      "year": 2016
    },
    {
      "comparability_notes": "Sector-wide miner work deaths, all causes, per İSİG annual reports as transcribed by the Wikipedia list. NOT comparable to the per-incident register (which covers listed accidents only) and never a rate: no exposure denominator.",
      "deaths": 93,
      "institution": "İSİG Meclisi (via tr.wikipedia list article)",
      "year": 2017
    },
    {
      "comparability_notes": "Sector-wide miner work deaths, all causes, per İSİG annual reports as transcribed by the Wikipedia list. NOT comparable to the per-incident register (which covers listed accidents only) and never a rate: no exposure denominator.",
      "deaths": 66,
      "institution": "İSİG Meclisi (via tr.wikipedia list article)",
      "year": 2018
    },
    {
      "comparability_notes": "Sector-wide miner work deaths, all causes, per İSİG annual reports as transcribed by the Wikipedia list. NOT comparable to the per-incident register (which covers listed accidents only) and never a rate: no exposure denominator.",
      "deaths": 63,
      "institution": "İSİG Meclisi (via tr.wikipedia list article)",
      "year": 2019
    },
    {
      "comparability_notes": "Sector-wide miner work deaths, all causes, per İSİG annual reports as transcribed by the Wikipedia list. NOT comparable to the per-incident register (which covers listed accidents only) and never a rate: no exposure denominator.",
      "deaths": 61,
      "institution": "İSİG Meclisi (via tr.wikipedia list article)",
      "year": 2020
    },
    {
      "comparability_notes": "Sector-wide miner work deaths, all causes, per İSİG annual reports as transcribed by the Wikipedia list. NOT comparable to the per-incident register (which covers listed accidents only) and never a rate: no exposure denominator.",
      "deaths": 70,
      "institution": "İSİG Meclisi (via tr.wikipedia list article)",
      "year": 2021
    },
    {
      "comparability_notes": "Sector-wide miner work deaths, all causes, per İSİG annual reports as transcribed by the Wikipedia list. NOT comparable to the per-incident register (which covers listed accidents only) and never a rate: no exposure denominator.",
      "deaths": 105,
      "institution": "İSİG Meclisi (via tr.wikipedia list article)",
      "year": 2022
    },
    {
      "comparability_notes": "Sector-wide miner work deaths, all causes, per İSİG annual reports as transcribed by the Wikipedia list. NOT comparable to the per-incident register (which covers listed accidents only) and never a rate: no exposure denominator.",
      "deaths": 51,
      "institution": "İSİG Meclisi (via tr.wikipedia list article)",
      "year": 2023
    },
    {
      "comparability_notes": "Sector-wide miner work deaths, all causes, per İSİG annual reports as transcribed by the Wikipedia list. NOT comparable to the per-incident register (which covers listed accidents only) and never a rate: no exposure denominator.",
      "deaths": 75,
      "institution": "İSİG Meclisi (via tr.wikipedia list article)",
      "year": 2024
    },
    {
      "comparability_notes": "Sector-wide miner work deaths, all causes, per İSİG annual reports as transcribed by the Wikipedia list. NOT comparable to the per-incident register (which covers listed accidents only) and never a rate: no exposure denominator.",
      "deaths": 61,
      "institution": "İSİG Meclisi (via tr.wikipedia list article)",
      "year": 2025
    }
  ],
  "citations": {
    "TR-MINE-1983-0001": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-1983-0002": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-1987-0001": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-1990-0001": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-1992-0001": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-1995-0001": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2003-0001": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2003-0002": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2004-0001": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2005-0001": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2006-0001": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2009-0001": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2010-0001": [
      {
        "organization": "Wikidata",
        "title": "Wikidata item Q4619016: Karadon Maden Kazası",
        "url": "https://www.wikidata.org/wiki/Q4619016"
      },
      {
        "organization": "Wikipedia (tr)",
        "title": "Karadon maden kazası",
        "url": "https://tr.wikipedia.org/wiki/Karadon_maden_kazas%C4%B1"
      }
    ],
    "TR-MINE-2010-0002": [
      {
        "organization": "Wikidata",
        "title": "Wikidata item Q6015822: Küçükdoğanca maden kazası",
        "url": "https://www.wikidata.org/wiki/Q6015822"
      },
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      },
      {
        "organization": "Wikipedia (tr)",
        "title": "Küçükdoğanca maden kazası",
        "url": "https://tr.wikipedia.org/wiki/K%C3%BC%C3%A7%C3%BCkdo%C4%9Fanca_maden_kazas%C4%B1"
      }
    ],
    "TR-MINE-2010-0003": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2013-0001": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2013-0002": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2014-0001": [
      {
        "organization": "Wikidata",
        "title": "Wikidata item Q16869476: Soma Faciası",
        "url": "https://www.wikidata.org/wiki/Q16869476"
      },
      {
        "organization": "Wikipedia (tr)",
        "title": "Soma Faciası",
        "url": "https://tr.wikipedia.org/wiki/Soma_Facias%C4%B1"
      }
    ],
    "TR-MINE-2014-0002": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2014-0003": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2014-0004": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2014-0005": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2014-0006": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2014-0007": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2014-0008": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2014-0009": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2014-0010": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2014-0011": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2015-0001": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2015-0002": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2015-0003": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2015-0004": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2015-0005": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2015-0006": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2019-0001": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2019-0002": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2022-0001": [
      {
        "organization": "Wikidata",
        "title": "Wikidata item Q114670156: Amasra maden kazası",
        "url": "https://www.wikidata.org/wiki/Q114670156"
      },
      {
        "organization": "Wikipedia (tr)",
        "title": "Amasra maden kazası",
        "url": "https://tr.wikipedia.org/wiki/Amasra_maden_kazas%C4%B1"
      }
    ],
    "TR-MINE-2024-0001": [
      {
        "organization": "Wikidata",
        "title": "Wikidata item Q124522721: Erzincan maden kazası",
        "url": "https://www.wikidata.org/wiki/Q124522721"
      },
      {
        "organization": "Wikipedia (en)",
        "title": "Çöpler mine disaster",
        "url": "https://en.wikipedia.org/wiki/%C3%87%C3%B6pler_mine_disaster"
      },
      {
        "organization": "Wikipedia (tr)",
        "title": "İliç maden kazası",
        "url": "https://tr.wikipedia.org/wiki/%C4%B0li%C3%A7_maden_kazas%C4%B1"
      }
    ],
    "TR-MINE-2024-0002": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2024-0003": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2025-0001": [
      {
        "organization": "Wikidata",
        "title": "Wikidata item Q134584262: Zara maden kazası",
        "url": "https://www.wikidata.org/wiki/Q134584262"
      },
      {
        "organization": "Wikipedia (tr)",
        "title": "Zara maden kazası",
        "url": "https://tr.wikipedia.org/wiki/Zara_maden_kazas%C4%B1"
      }
    ],
    "TR-MINE-2025-0002": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2025-0003": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2025-0004": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2025-0005": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ],
    "TR-MINE-2025-0006": [
      {
        "organization": "Wikipedia (tr)",
        "title": "Türkiye'deki madencilik kazaları listesi",
        "url": "https://tr.wikipedia.org/wiki/T%C3%BCrkiye%27deki_madencilik_kazalar%C4%B1_listesi"
      }
    ]
  },
  "classifications": {
    "TR-MINE-1983-0001": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-1983-0002": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-1987-0001": [
      {
        "assertion_status": "reported",
        "code": "roof_or_ground_collapse",
        "label_en": "roof or ground collapse",
        "label_tr": "tavan/göçük",
        "system": "project_event_mechanism"
      }
    ],
    "TR-MINE-1990-0001": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-1992-0001": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-1995-0001": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2003-0001": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2003-0002": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2004-0001": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2005-0001": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2006-0001": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2009-0001": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2010-0001": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2010-0002": [
      {
        "assertion_status": "reported",
        "code": "roof_or_ground_collapse",
        "label_en": "roof or ground collapse",
        "label_tr": "tavan/göçük",
        "system": "project_event_mechanism"
      }
    ],
    "TR-MINE-2013-0002": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2014-0001": [
      {
        "assertion_status": "reported",
        "code": "fire",
        "label_en": "fire",
        "label_tr": "yangın",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "fire",
        "label_en": "fire",
        "label_tr": "yangın",
        "system": "project_hazard"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2014-0002": [
      {
        "assertion_status": "reported",
        "code": "roof_or_ground_collapse",
        "label_en": "roof or ground collapse",
        "label_tr": "tavan/göçük",
        "system": "project_event_mechanism"
      }
    ],
    "TR-MINE-2014-0003": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2014-0004": [
      {
        "assertion_status": "reported",
        "code": "flooding_or_inrush",
        "label_en": "flooding or inrush",
        "label_tr": "su baskını/ani su geliri",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "water_ingress",
        "label_en": "water ingress",
        "label_tr": "su geliri",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2014-0007": [
      {
        "assertion_status": "reported",
        "code": "roof_or_ground_collapse",
        "label_en": "roof or ground collapse",
        "label_tr": "tavan/göçük",
        "system": "project_event_mechanism"
      }
    ],
    "TR-MINE-2014-0009": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2014-0010": [
      {
        "assertion_status": "reported",
        "code": "roof_or_ground_collapse",
        "label_en": "roof or ground collapse",
        "label_tr": "tavan/göçük",
        "system": "project_event_mechanism"
      }
    ],
    "TR-MINE-2014-0011": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2015-0001": [
      {
        "assertion_status": "reported",
        "code": "roof_or_ground_collapse",
        "label_en": "roof or ground collapse",
        "label_tr": "tavan/göçük",
        "system": "project_event_mechanism"
      }
    ],
    "TR-MINE-2015-0002": [
      {
        "assertion_status": "reported",
        "code": "roof_or_ground_collapse",
        "label_en": "roof or ground collapse",
        "label_tr": "tavan/göçük",
        "system": "project_event_mechanism"
      }
    ],
    "TR-MINE-2015-0004": [
      {
        "assertion_status": "reported",
        "code": "roof_or_ground_collapse",
        "label_en": "roof or ground collapse",
        "label_tr": "tavan/göçük",
        "system": "project_event_mechanism"
      }
    ],
    "TR-MINE-2019-0001": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2022-0001": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2024-0003": [
      {
        "assertion_status": "reported",
        "code": "roof_or_ground_collapse",
        "label_en": "roof or ground collapse",
        "label_tr": "tavan/göçük",
        "system": "project_event_mechanism"
      }
    ],
    "TR-MINE-2025-0003": [
      {
        "assertion_status": "reported",
        "code": "gas_explosion",
        "label_en": "gas explosion",
        "label_tr": "gaz (grizu) patlaması",
        "system": "project_event_mechanism"
      },
      {
        "assertion_status": "reported",
        "code": "methane",
        "label_en": "methane",
        "label_tr": "metan (grizu)",
        "system": "project_hazard"
      }
    ],
    "TR-MINE-2025-0004": [
      {
        "assertion_status": "reported",
        "code": "roof_or_ground_collapse",
        "label_en": "roof or ground collapse",
        "label_tr": "tavan/göçük",
        "system": "project_event_mechanism"
      }
    ],
    "TR-MINE-2025-0006": [
      {
        "assertion_status": "reported",
        "code": "roof_or_ground_collapse",
        "label_en": "roof or ground collapse",
        "label_tr": "tavan/göçük",
        "system": "project_event_mechanism"
      }
    ]
  },
  "export_timestamp": "2026-07-14T17:40:21Z",
  "incidents": [
    {
      "canonical_title_en": null,
      "canonical_title_tr": "1983 Armutçuk grizu faciası",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 103,
      "incident_end_datetime": null,
      "incident_start_datetime": "1983-03-07T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "67",
      "province_name": "Zonguldak",
      "public_incident_id": "TR-MINE-1983-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Zonguldak (1983-04-10)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 10,
      "incident_end_datetime": null,
      "incident_start_datetime": "1983-04-10T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "67",
      "province_name": "Zonguldak",
      "public_incident_id": "TR-MINE-1983-0002",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Zonguldak (1987-01-01)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "month",
      "district_code": null,
      "fatalities_current": 8,
      "incident_end_datetime": null,
      "incident_start_datetime": "1987-01-01T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "67",
      "province_name": "Zonguldak",
      "public_incident_id": "TR-MINE-1987-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Bartın (1990-01-31)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 5,
      "incident_end_datetime": null,
      "incident_start_datetime": "1990-01-31T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "74",
      "province_name": "Bartın",
      "public_incident_id": "TR-MINE-1990-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "1992 Kozlu grizu faciası",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 263,
      "incident_end_datetime": null,
      "incident_start_datetime": "1992-03-03T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "67",
      "province_name": "Zonguldak",
      "public_incident_id": "TR-MINE-1992-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Yozgat (1995-03-26)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 38,
      "incident_end_datetime": null,
      "incident_start_datetime": "1995-03-26T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "66",
      "province_name": "Yozgat",
      "public_incident_id": "TR-MINE-1995-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Karaman (2003-11-22)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 10,
      "incident_end_datetime": null,
      "incident_start_datetime": "2003-11-22T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "70",
      "province_name": "Karaman",
      "public_incident_id": "TR-MINE-2003-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Erzurum (2003-08-08)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 7,
      "incident_end_datetime": null,
      "incident_start_datetime": "2003-08-08T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "25",
      "province_name": "Erzurum",
      "public_incident_id": "TR-MINE-2003-0002",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Çorum (2004-08-01)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "month",
      "district_code": null,
      "fatalities_current": 3,
      "incident_end_datetime": null,
      "incident_start_datetime": "2004-08-01T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "19",
      "province_name": "Çorum",
      "public_incident_id": "TR-MINE-2004-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Kütahya (2005-04-01)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "month",
      "district_code": null,
      "fatalities_current": 18,
      "incident_end_datetime": null,
      "incident_start_datetime": "2005-04-01T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "43",
      "province_name": "Kütahya",
      "public_incident_id": "TR-MINE-2005-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Balıkesir (2006-06-01)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 17,
      "incident_end_datetime": null,
      "incident_start_datetime": "2006-06-01T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "10",
      "province_name": "Balıkesir",
      "public_incident_id": "TR-MINE-2006-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Bursa (2009-12-10)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 19,
      "incident_end_datetime": null,
      "incident_start_datetime": "2009-12-10T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "16",
      "province_name": "Bursa",
      "public_incident_id": "TR-MINE-2009-0001",
      "settlement": null
    },
    {
      "canonical_title_en": "2010 Zonguldak mine disaster",
      "canonical_title_tr": "Karadon Maden Kazası",
      "casualty_status": null,
      "coordinate_precision": "facility_approximate",
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 30,
      "incident_end_datetime": null,
      "incident_start_datetime": "2010-05-17T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": 41.485865,
      "location_uncertainty_m": null,
      "longitude": 31.864072,
      "missing_current": null,
      "province_code": "67",
      "province_name": "Zonguldak",
      "public_incident_id": "TR-MINE-2010-0001",
      "settlement": null
    },
    {
      "canonical_title_en": "Küçükdoğanca mining accident",
      "canonical_title_tr": "Küçükdoğanca maden kazası",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 3,
      "incident_end_datetime": null,
      "incident_start_datetime": "2010-07-07T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "22",
      "province_name": "Edirne",
      "public_incident_id": "TR-MINE-2010-0002",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Bursa (2010-10-26)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 2,
      "incident_end_datetime": null,
      "incident_start_datetime": "2010-10-26T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "16",
      "province_name": "Bursa",
      "public_incident_id": "TR-MINE-2010-0003",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Manisa (2013-01-18)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2013-01-18T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "45",
      "province_name": "Manisa",
      "public_incident_id": "TR-MINE-2013-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Zonguldak (2013-01-08)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 8,
      "incident_end_datetime": null,
      "incident_start_datetime": "2013-01-08T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "67",
      "province_name": "Zonguldak",
      "public_incident_id": "TR-MINE-2013-0002",
      "settlement": null
    },
    {
      "canonical_title_en": "Soma mine disaster",
      "canonical_title_tr": "Soma Faciası",
      "casualty_status": null,
      "coordinate_precision": "facility_approximate",
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 301,
      "incident_end_datetime": null,
      "incident_start_datetime": "2014-05-13T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": 39.077194,
      "location_uncertainty_m": null,
      "longitude": 27.525258,
      "missing_current": null,
      "province_code": "45",
      "province_name": "Manisa",
      "public_incident_id": "TR-MINE-2014-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Bartın (2014-11-01)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 3,
      "incident_end_datetime": null,
      "incident_start_datetime": "2014-11-01T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "74",
      "province_name": "Bartın",
      "public_incident_id": "TR-MINE-2014-0002",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Amasya (2014-06-29)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 5,
      "incident_end_datetime": null,
      "incident_start_datetime": "2014-06-29T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "05",
      "province_name": "Amasya",
      "public_incident_id": "TR-MINE-2014-0003",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Karaman (2014-10-28)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 18,
      "incident_end_datetime": null,
      "incident_start_datetime": "2014-10-28T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "70",
      "province_name": "Karaman",
      "public_incident_id": "TR-MINE-2014-0004",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Elazığ (2014-11-06)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2014-11-06T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "23",
      "province_name": "Elazığ",
      "public_incident_id": "TR-MINE-2014-0005",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Kahramanmaraş (2014-06-01)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2014-06-01T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "46",
      "province_name": "Kahramanmaraş",
      "public_incident_id": "TR-MINE-2014-0006",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Şırnak (2014-06-11)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 3,
      "incident_end_datetime": null,
      "incident_start_datetime": "2014-06-11T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "73",
      "province_name": "Şırnak",
      "public_incident_id": "TR-MINE-2014-0007",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Bingöl (2014-11-19)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2014-11-19T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "12",
      "province_name": "Bingöl",
      "public_incident_id": "TR-MINE-2014-0008",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Nevşehir (2014-04-26)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2014-04-26T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "50",
      "province_name": "Nevşehir",
      "public_incident_id": "TR-MINE-2014-0009",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Şırnak (2014-06-18)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2014-06-18T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "73",
      "province_name": "Şırnak",
      "public_incident_id": "TR-MINE-2014-0010",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Edirne (2014-11-13)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 3,
      "incident_end_datetime": null,
      "incident_start_datetime": "2014-11-13T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "22",
      "province_name": "Edirne",
      "public_incident_id": "TR-MINE-2014-0011",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Sivas (2015-01-21)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2015-01-21T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "58",
      "province_name": "Sivas",
      "public_incident_id": "TR-MINE-2015-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Zonguldak (2015-03-10)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2015-03-10T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "67",
      "province_name": "Zonguldak",
      "public_incident_id": "TR-MINE-2015-0002",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Muğla (2015-02-07)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2015-02-07T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "48",
      "province_name": "Muğla",
      "public_incident_id": "TR-MINE-2015-0003",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Amasya (2015-06-08)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2015-06-08T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "05",
      "province_name": "Amasya",
      "public_incident_id": "TR-MINE-2015-0004",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Ankara (2015-07-27)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2015-07-27T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "06",
      "province_name": "Ankara",
      "public_incident_id": "TR-MINE-2015-0005",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Muğla (2015-07-21)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2015-07-21T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "48",
      "province_name": "Muğla",
      "public_incident_id": "TR-MINE-2015-0006",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Zonguldak (2019-12-01)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "month",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2019-12-01T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "67",
      "province_name": "Zonguldak",
      "public_incident_id": "TR-MINE-2019-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Manisa (2019-02-03)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2019-02-03T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "45",
      "province_name": "Manisa",
      "public_incident_id": "TR-MINE-2019-0002",
      "settlement": null
    },
    {
      "canonical_title_en": "Amasra mine explosion",
      "canonical_title_tr": "Amasra maden kazası",
      "casualty_status": null,
      "coordinate_precision": "facility_approximate",
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 42,
      "incident_end_datetime": null,
      "incident_start_datetime": "2022-10-14T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": 41.721848,
      "location_uncertainty_m": null,
      "longitude": 32.349063,
      "missing_current": null,
      "province_code": "74",
      "province_name": "Bartın",
      "public_incident_id": "TR-MINE-2022-0001",
      "settlement": null
    },
    {
      "canonical_title_en": "Çöpler mine disaster",
      "canonical_title_tr": "Erzincan maden kazası",
      "casualty_status": null,
      "coordinate_precision": "facility_approximate",
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 9,
      "incident_end_datetime": null,
      "incident_start_datetime": "2024-02-13T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": 39.439234,
      "location_uncertainty_m": null,
      "longitude": 38.536482,
      "missing_current": null,
      "province_code": "24",
      "province_name": "Erzincan",
      "public_incident_id": "TR-MINE-2024-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Manisa (2024-10-22)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2024-10-22T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "45",
      "province_name": "Manisa",
      "public_incident_id": "TR-MINE-2024-0002",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Zonguldak (2024-08-08)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2024-08-08T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "67",
      "province_name": "Zonguldak",
      "public_incident_id": "TR-MINE-2024-0003",
      "settlement": null
    },
    {
      "canonical_title_en": "Zara mine explosion",
      "canonical_title_tr": "Zara maden kazası",
      "casualty_status": null,
      "coordinate_precision": "facility_approximate",
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 1,
      "incident_end_datetime": null,
      "incident_start_datetime": "2025-05-26T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": 39.69449,
      "location_uncertainty_m": null,
      "longitude": 38.00883,
      "missing_current": null,
      "province_code": "58",
      "province_name": "Sivas",
      "public_incident_id": "TR-MINE-2025-0001",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Aydın (2025-01-22)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 4,
      "incident_end_datetime": null,
      "incident_start_datetime": "2025-01-22T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "09",
      "province_name": "Aydın",
      "public_incident_id": "TR-MINE-2025-0002",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Balıkesir (2025-01-22)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 18,
      "incident_end_datetime": null,
      "incident_start_datetime": "2025-01-22T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "10",
      "province_name": "Balıkesir",
      "public_incident_id": "TR-MINE-2025-0003",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Zonguldak (2025-01-22)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 3,
      "incident_end_datetime": null,
      "incident_start_datetime": "2025-01-22T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "67",
      "province_name": "Zonguldak",
      "public_incident_id": "TR-MINE-2025-0004",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Manisa (2025-01-22)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 3,
      "incident_end_datetime": null,
      "incident_start_datetime": "2025-01-22T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "45",
      "province_name": "Manisa",
      "public_incident_id": "TR-MINE-2025-0005",
      "settlement": null
    },
    {
      "canonical_title_en": null,
      "canonical_title_tr": "Maden kazası — Çanakkale (2025-01-22)",
      "casualty_status": null,
      "coordinate_precision": null,
      "date_precision": "exact_date",
      "district_code": null,
      "fatalities_current": 3,
      "incident_end_datetime": null,
      "incident_start_datetime": "2025-01-22T00:00:00+03:00",
      "incident_status": "in_scope",
      "injuries_current": null,
      "latitude": null,
      "location_uncertainty_m": null,
      "longitude": null,
      "missing_current": null,
      "province_code": "17",
      "province_name": "Çanakkale",
      "public_incident_id": "TR-MINE-2025-0006",
      "settlement": null
    }
  ],
  "pipeline": {
    "claims_awaiting_review": 10,
    "claims_total": 435,
    "decisions_total": 313,
    "published_incidents": 46,
    "records_in_review": 32,
    "source_documents": 28
  },
  "province_centroids": {
    "01": {
      "label_tr": "Adana",
      "latitude": 37.36833,
      "longitude": 35.70611
    },
    "02": {
      "label_tr": "Adıyaman",
      "latitude": 37.76,
      "longitude": 38.27861
    },
    "03": {
      "label_tr": "Afyonkarahisar",
      "latitude": 38.75667,
      "longitude": 30.53972
    },
    "04": {
      "label_tr": "Ağrı",
      "latitude": 39.71861,
      "longitude": 43.05222
    },
    "05": {
      "label_tr": "Amasya",
      "latitude": 40.65028,
      "longitude": 35.83278
    },
    "06": {
      "label_tr": "Ankara",
      "latitude": 39.92639,
      "longitude": 32.85611
    },
    "07": {
      "label_tr": "Antalya",
      "latitude": 37.18167,
      "longitude": 30.93333
    },
    "08": {
      "label_tr": "Artvin",
      "latitude": 41.13333,
      "longitude": 41.85
    },
    "09": {
      "label_tr": "Aydın",
      "latitude": 37.72833,
      "longitude": 27.93722
    },
    "10": {
      "label_tr": "Balıkesir",
      "latitude": 39.74083,
      "longitude": 27.81917
    },
    "11": {
      "label_tr": "Bilecik",
      "latitude": 40.0,
      "longitude": 30.16667
    },
    "12": {
      "label_tr": "Bingöl",
      "latitude": 39.04111,
      "longitude": 40.67583
    },
    "13": {
      "label_tr": "Bitlis",
      "latitude": 38.52583,
      "longitude": 42.38778
    },
    "14": {
      "label_tr": "Bolu",
      "latitude": 40.67917,
      "longitude": 31.55833
    },
    "15": {
      "label_tr": "Burdur",
      "latitude": 37.42389,
      "longitude": 30.08444
    },
    "16": {
      "label_tr": "Bursa",
      "latitude": 40.15,
      "longitude": 29.02083
    },
    "17": {
      "label_tr": "Çanakkale",
      "latitude": 40.15056,
      "longitude": 26.41111
    },
    "18": {
      "label_tr": "Çankırı",
      "latitude": 40.73556,
      "longitude": 33.36611
    },
    "19": {
      "label_tr": "Çorum",
      "latitude": 40.55222,
      "longitude": 34.95389
    },
    "20": {
      "label_tr": "Denizli",
      "latitude": 37.84016,
      "longitude": 29.06982
    },
    "21": {
      "label_tr": "Diyarbakır",
      "latitude": 38.14222,
      "longitude": 40.27111
    },
    "22": {
      "label_tr": "Edirne",
      "latitude": 41.12,
      "longitude": 26.52056
    },
    "23": {
      "label_tr": "Elazığ",
      "latitude": 38.6675,
      "longitude": 39.35972
    },
    "24": {
      "label_tr": "Erzincan",
      "latitude": 39.67833,
      "longitude": 39.33
    },
    "25": {
      "label_tr": "Erzurum",
      "latitude": 40.06306,
      "longitude": 41.56694
    },
    "26": {
      "label_tr": "Eskişehir",
      "latitude": 39.6825,
      "longitude": 31.0725
    },
    "27": {
      "label_tr": "Gaziantep",
      "latitude": 37.08333,
      "longitude": 37.33333
    },
    "28": {
      "label_tr": "Giresun",
      "latitude": 40.57972,
      "longitude": 38.59444
    },
    "29": {
      "label_tr": "Gümüşhane",
      "latitude": 40.38806,
      "longitude": 39.41861
    },
    "30": {
      "label_tr": "Hakkari",
      "latitude": 37.46611,
      "longitude": 44.06444
    },
    "31": {
      "label_tr": "Hatay",
      "latitude": 36.2,
      "longitude": 36.15
    },
    "32": {
      "label_tr": "Isparta",
      "latitude": 37.95667,
      "longitude": 30.96083
    },
    "33": {
      "label_tr": "Mersin",
      "latitude": 36.67861,
      "longitude": 33.80528
    },
    "34": {
      "label_tr": "İstanbul",
      "latitude": 41.01222,
      "longitude": 28.97611
    },
    "35": {
      "label_tr": "İzmir",
      "latitude": 38.41889,
      "longitude": 27.12972
    },
    "36": {
      "label_tr": "Kars",
      "latitude": 40.45472,
      "longitude": 43.06028
    },
    "37": {
      "label_tr": "Kastamonu",
      "latitude": 41.51944,
      "longitude": 33.68972
    },
    "38": {
      "label_tr": "Kayseri",
      "latitude": 38.73695,
      "longitude": 35.49683
    },
    "39": {
      "label_tr": "Kırklareli",
      "latitude": 41.68111,
      "longitude": 27.47139
    },
    "40": {
      "label_tr": "Kırşehir",
      "latitude": 39.32389,
      "longitude": 34.12917
    },
    "41": {
      "label_tr": "Kocaeli",
      "latitude": 40.76444,
      "longitude": 29.945
    },
    "43": {
      "label_tr": "Kütahya",
      "latitude": 39.30472,
      "longitude": 29.59
    },
    "44": {
      "label_tr": "Malatya",
      "latitude": 38.34806,
      "longitude": 38.31778
    },
    "45": {
      "label_tr": "Manisa",
      "latitude": 38.74944,
      "longitude": 28.12278
    },
    "46": {
      "label_tr": "Kahramanmaraş",
      "latitude": 37.89833,
      "longitude": 36.97111
    },
    "47": {
      "label_tr": "Mardin",
      "latitude": 37.31775,
      "longitude": 40.71533
    },
    "48": {
      "label_tr": "Muğla",
      "latitude": 37.03028,
      "longitude": 28.50639
    },
    "49": {
      "label_tr": "Muş",
      "latitude": 39.00056,
      "longitude": 41.82722
    },
    "50": {
      "label_tr": "Nevşehir",
      "latitude": 38.78167,
      "longitude": 34.68806
    },
    "51": {
      "label_tr": "Niğde",
      "latitude": 37.91583,
      "longitude": 34.69361
    },
    "52": {
      "label_tr": "Ordu",
      "latitude": 40.81139,
      "longitude": 37.54056
    },
    "53": {
      "label_tr": "Rize",
      "latitude": 40.93167,
      "longitude": 40.84778
    },
    "54": {
      "label_tr": "Sakarya",
      "latitude": 40.69722,
      "longitude": 30.45667
    },
    "55": {
      "label_tr": "Samsun",
      "latitude": 41.20444,
      "longitude": 36.00722
    },
    "56": {
      "label_tr": "Siirt",
      "latitude": 37.93,
      "longitude": 42.27028
    },
    "57": {
      "label_tr": "Sinop",
      "latitude": 41.60917,
      "longitude": 34.90194
    },
    "58": {
      "label_tr": "Sivas",
      "latitude": 39.75028,
      "longitude": 37.01611
    },
    "59": {
      "label_tr": "Tekirdağ",
      "latitude": 40.97778,
      "longitude": 27.51833
    },
    "60": {
      "label_tr": "Tokat",
      "latitude": 40.35278,
      "longitude": 36.56444
    },
    "61": {
      "label_tr": "Trabzon",
      "latitude": 40.78056,
      "longitude": 39.81222
    },
    "62": {
      "label_tr": "Uşak",
      "latitude": 38.52389,
      "longitude": 29.34194
    },
    "63": {
      "label_tr": "Şanlıurfa",
      "latitude": 37.25417,
      "longitude": 39.0425
    },
    "65": {
      "label_tr": "Van",
      "latitude": 38.50111,
      "longitude": 43.37306
    },
    "66": {
      "label_tr": "Yozgat",
      "latitude": 39.66944,
      "longitude": 35.26917
    },
    "67": {
      "label_tr": "Zonguldak",
      "latitude": 41.32056,
      "longitude": 31.73361
    },
    "68": {
      "label_tr": "Aksaray",
      "latitude": 38.43083,
      "longitude": 33.86222
    },
    "69": {
      "label_tr": "Bayburt",
      "latitude": 40.23667,
      "longitude": 40.22361
    },
    "70": {
      "label_tr": "Karaman",
      "latitude": 37.01667,
      "longitude": 33.08333
    },
    "71": {
      "label_tr": "Kırıkkale",
      "latitude": 39.86972,
      "longitude": 33.71611
    },
    "72": {
      "label_tr": "Batman",
      "latitude": 38.08194,
      "longitude": 41.40722
    },
    "73": {
      "label_tr": "Şırnak",
      "latitude": 37.51917,
      "longitude": 42.45417
    },
    "74": {
      "label_tr": "Bartın",
      "latitude": 41.60444,
      "longitude": 32.51111
    },
    "75": {
      "label_tr": "Ardahan",
      "latitude": 41.11306,
      "longitude": 42.82083
    },
    "76": {
      "label_tr": "Iğdır",
      "latitude": 39.89361,
      "longitude": 43.99778
    },
    "77": {
      "label_tr": "Yalova",
      "latitude": 40.64417,
      "longitude": 29.19361
    },
    "78": {
      "label_tr": "Karabük",
      "latitude": 41.22361,
      "longitude": 32.64028
    },
    "79": {
      "label_tr": "Kilis",
      "latitude": 36.80083,
      "longitude": 37.12389
    },
    "80": {
      "label_tr": "Osmaniye",
      "latitude": 37.22806,
      "longitude": 36.2125
    },
    "81": {
      "label_tr": "Düzce",
      "latitude": 40.94694,
      "longitude": 31.23806
    }
  },
  "schema_version": "001"
};
