"""Self-contained artifact build of the public page.

Role in the evidence flow: packages the same reviewed public payload as the
dashboard into one dependency-free HTML file (``dashboard/artifact.html``)
for hosting environments that block external requests. The page template is
``dashboard/index.html`` itself — the artifact strips the Leaflet/vendor
references and embeds the data inline, so the page's built-in SVG map
fallback renders instead of tiles. One template, two outputs.
"""

from __future__ import annotations

import json
import re
import sqlite3
from pathlib import Path

from mining_accidents.dashboard import DEFAULT_PUBLIC_DIR, build_payload

DEFAULT_TEMPLATE = Path("dashboard/index.html")
DEFAULT_ARTIFACT = Path("dashboard/artifact.html")

HEADER = (
    "<!-- GENERATED by `mining-accidents build-artifact` from dashboard/index.html\n"
    "     — do not edit. Self-contained: embedded data, vector map, no external\n"
    "     requests. Written without <html>/<head>/<body> wrapper tags for\n"
    "     artifact hosting; browsers render it standalone regardless. -->\n"
)


def _extract(template_html: str, pattern: str, what: str) -> str:
    match = re.search(pattern, template_html, re.DOTALL)
    if not match:
        raise ValueError(f"could not find {what} in the dashboard template")
    return match.group(0)


def build_artifact(
    conn: sqlite3.Connection,
    public_dir: str | Path = DEFAULT_PUBLIC_DIR,
    template_path: str | Path = DEFAULT_TEMPLATE,
    output_path: str | Path = DEFAULT_ARTIFACT,
) -> Path:
    template = Path(template_path).read_text(encoding="utf-8")
    title = _extract(template, r"<title>.*?</title>", "<title>")
    style = _extract(template, r"<style>.*?</style>", "<style> block")
    main = _extract(template, r"<main>.*?</main>", "<main> block")
    script = _extract(template, r"<script>\s*\(function.*?</script>", "page script")

    # The artifact host owns <body>, so the template's .viz-root class never
    # gets attached — rebind the theme tokens/styles to body itself.
    style = style.replace("body.viz-root", "body").replace(".viz-root", "body")

    payload = build_payload(conn, public_dir)
    embedded = (
        "<script>window.MINING_DATA = "
        + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        + ";</script>\n"
    )
    output = Path(output_path)
    output.write_text(
        HEADER + title + "\n" + style + "\n" + embedded + main + "\n" + script + "\n",
        encoding="utf-8",
    )
    return output
