"""Dashboard data builder.

Role in the evidence flow: packages the PUBLIC export (never the raw
database) plus aggregate pipeline-status counts into ``dashboard/data.js``
for the static visualization. The dashboard therefore can only ever show
records that passed the full publication threshold; everything else appears
solely as an aggregate "in review" count. Deterministic output
(sort_keys, stable ordering) like the export itself.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from mining_accidents import vocabularies

DEFAULT_PUBLIC_DIR = Path("data/public")
DEFAULT_OUTPUT = Path("dashboard/data.js")

HEADER = (
    "// GENERATED by `mining-accidents build-dashboard` — do not edit.\n"
    "// Contents mirror data/public/ (the reviewed public export) plus\n"
    "// aggregate pipeline-status counts. See dashboard/README.md.\n"
)


def _citations(public_dir: Path) -> dict[str, list[dict[str, str]]]:
    import csv

    citations: dict[str, list[dict[str, str]]] = {}
    with (public_dir / "sources.csv").open(encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh):
            entry = {
                "organization": row["source_organization"],
                "title": row["title"],
                "url": row["url"],
            }
            bucket = citations.setdefault(row["public_incident_id"], [])
            if entry not in bucket:
                bucket.append(entry)
    return citations


def _classifications(public_dir: Path) -> dict[str, list[dict[str, str]]]:
    import csv

    result: dict[str, list[dict[str, str]]] = {}
    with (public_dir / "incident_classifications.csv").open(encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh):
            result.setdefault(row["public_incident_id"], []).append(
                {
                    "system": row["classification_system"],
                    "code": row["classification_code"],
                    "label_tr": row["classification_label_tr"],
                    "label_en": row["classification_label_en"],
                    "assertion_status": row["assertion_status"],
                }
            )
    return result


def _aggregates(conn: sqlite3.Connection) -> list[dict[str, object]]:
    """İSİG context series (aggregate table). Comparability notes travel along."""
    return [
        {
            "year": int(row["period_start"][:4]),
            "deaths": int(row["numerator"]),
            "institution": row["reporting_institution"],
            "comparability_notes": row["comparability_notes"],
        }
        for row in conn.execute(
            "SELECT period_start, numerator, reporting_institution, comparability_notes "
            "FROM aggregate_occupational_statistics WHERE unit = 'deaths' "
            "ORDER BY period_start"
        )
    ]


def _province_centroids() -> dict[str, dict[str, float | str]]:
    """Display-only reference points (Wikidata CC0) for province-level marks.

    Never incident locations: the dashboard renders these as clearly-labeled
    centroid symbols per the data contract."""
    import csv

    result: dict[str, dict[str, float | str]] = {}
    with Path("data/vocabularies/province_centroids.csv").open(
        encoding="utf-8", newline=""
    ) as fh:
        for row in csv.DictReader(fh):
            result[row["code"]] = {
                "label_tr": row["label_tr"],
                "latitude": float(row["latitude"]),
                "longitude": float(row["longitude"]),
            }
    return result


def _pipeline_status(conn: sqlite3.Connection) -> dict[str, int]:
    def count(sql: str) -> int:
        return int(conn.execute(sql).fetchone()[0])

    return {
        "published_incidents": count(
            "SELECT COUNT(*) FROM incidents WHERE publication_status IN "
            "('publishable', 'published')"
        ),
        "records_in_review": count(
            "SELECT COUNT(*) FROM incidents WHERE publication_status NOT IN "
            "('publishable', 'published', 'withdrawn')"
        ),
        "claims_awaiting_review": count(
            "SELECT COUNT(*) FROM claims WHERE review_status = 'needs_review'"
        ),
        "source_documents": count("SELECT COUNT(*) FROM source_documents"),
        "claims_total": count("SELECT COUNT(*) FROM claims"),
        "decisions_total": count("SELECT COUNT(*) FROM claim_decisions"),
    }


def build_dashboard_data(
    conn: sqlite3.Connection,
    public_dir: str | Path = DEFAULT_PUBLIC_DIR,
    output_path: str | Path = DEFAULT_OUTPUT,
) -> Path:
    public_dir = Path(public_dir)
    incidents = json.loads((public_dir / "incidents.json").read_text(encoding="utf-8"))
    manifest = json.loads((public_dir / "export_manifest.json").read_text(encoding="utf-8"))
    provinces = {e.code: e.label_tr for e in vocabularies.load_vocabulary("turkey_admin_areas")}
    for incident in incidents:
        incident["province_name"] = provinces.get(incident.get("province_code") or "", "")

    payload = {
        "incidents": incidents,
        "citations": _citations(public_dir),
        "classifications": _classifications(public_dir),
        "aggregates": _aggregates(conn),
        "province_centroids": _province_centroids(),
        "pipeline": _pipeline_status(conn),
        "export_timestamp": manifest["export_timestamp"],
        "schema_version": manifest["db_schema_version"],
    }
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        HEADER
        + "window.MINING_DATA = "
        + json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
        + ";\n",
        encoding="utf-8",
    )
    return output_path
