"""Dashboard data builder.

Role in the evidence flow: packages the PUBLIC export (never the raw
database) plus aggregate pipeline-status counts into ``dashboard/data.js``
for the static visualization. The dashboard therefore can only ever show
records that passed the full publication threshold; everything else appears
solely as an aggregate "in review" count. Deterministic output
(sort_keys, stable ordering) like the export itself.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from mining_accidents import analysis, vocabularies

DEFAULT_PUBLIC_DIR = Path("data/public")
DEFAULT_OUTPUT = Path("dashboard/data.js")

HEADER = (
    "// GENERATED by `mining-accidents build-dashboard` — do not edit.\n"
    "// Contents mirror data/public/ (the reviewed public export) plus\n"
    "// aggregate pipeline-status counts. See dashboard/README.md.\n"
)


def _citations(public_dir: Path) -> dict[str, list[dict[str, str]]]:
    import csv

    citations: dict[str, list[dict[str, str]]] = {}
    with (public_dir / "sources.csv").open(encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh):
            entry = {
                "organization": row["source_organization"],
                "title": row["title"],
                "url": row["url"],
            }
            bucket = citations.setdefault(row["public_incident_id"], [])
            if entry not in bucket:
                bucket.append(entry)
    return citations


def _classifications(public_dir: Path) -> dict[str, list[dict[str, str]]]:
    import csv

    result: dict[str, list[dict[str, str]]] = {}
    with (public_dir / "incident_classifications.csv").open(encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh):
            result.setdefault(row["public_incident_id"], []).append(
                {
                    "system": row["classification_system"],
                    "code": row["classification_code"],
                    "label_tr": row["classification_label_tr"],
                    "label_en": row["classification_label_en"],
                    "assertion_status": row["assertion_status"],
                }
            )
    return result


def _aggregates(conn: sqlite3.Connection) -> list[dict[str, object]]:
    """İSİG context series (aggregate table). Comparability notes travel along."""
    return [
        {
            "year": int(row["period_start"][:4]),
            "deaths": int(row["numerator"]),
            "institution": row["reporting_institution"],
            "comparability_notes": row["comparability_notes"],
        }
        for row in conn.execute(
            "SELECT period_start, numerator, reporting_institution, comparability_notes "
            "FROM aggregate_occupational_statistics WHERE unit = 'deaths' "
            "ORDER BY period_start"
        )
    ]


def _sites(public_dir: Path) -> list[dict[str, object]]:
    """Active-sites context registry from the public export (partial coverage:
    open structured sources only — never presented as a complete register)."""
    import csv

    facilities_csv = public_dir / "facilities.csv"
    if not facilities_csv.exists():
        return []
    operators: dict[str, list[dict[str, str]]] = {}
    roles_csv = public_dir / "facility_organization_roles.csv"
    if roles_csv.exists():
        with roles_csv.open(encoding="utf-8", newline="") as fh:
            for row in csv.DictReader(fh):
                operators.setdefault(row["facility_ref"], []).append(
                    {
                        "name": row["organization_name_tr"],
                        "country_code": row["organization_country_code"],
                        "country_label": row["organization_country_label"],
                        "role": row["role"],
                        "assertion_status": row["assertion_status"],
                    }
                )
    sites = []
    with facilities_csv.open(encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh):
            sites.append(
                {
                    "ref": row["facility_ref"],
                    "name": row["facility_name_tr"],
                    "type": row["facility_type"],
                    "commodity_code": row["commodity_code"],
                    "commodity_label": row["commodity_label"],
                    "province_code": row["province_code"],
                    "latitude": float(row["latitude"]) if row["latitude"] else None,
                    "longitude": float(row["longitude"]) if row["longitude"] else None,
                    "coordinate_precision": row["coordinate_precision"],
                    "status": row["operational_status"],
                    "source_url": row["source_url"],
                    "organizations": operators.get(row["facility_ref"], []),
                }
            )
    return sites


def _province_centroids() -> dict[str, dict[str, float | str]]:
    """Display-only reference points (Wikidata CC0) for province-level marks.

    Never incident locations: the dashboard renders these as clearly-labeled
    centroid symbols per the data contract."""
    import csv

    result: dict[str, dict[str, float | str]] = {}
    with Path("data/vocabularies/province_centroids.csv").open(encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh):
            result[row["code"]] = {
                "label_tr": row["label_tr"],
                "latitude": float(row["latitude"]),
                "longitude": float(row["longitude"]),
            }
    return result


PROVINCES_GEOJSON = Path("data/reference/tur_provinces.geo.json")
_PROJ = {"lon0": 25.3, "lon1": 45.1, "lat0": 35.5, "lat1": 42.4, "k": 46.0}


def _map_vector(
    incidents: list[dict[str, object]],
    centroids: dict[str, dict[str, float | str]],
    sites: list[dict[str, object]] | None = None,
) -> dict[str, object]:
    """Projected vector map (Türkiye province boundaries + marks) for
    tile-free rendering.

    Geometry: Natural Earth 10m admin-1 (public domain), one path per
    province. Simple equirectangular projection; display-only geometry,
    not evidence."""
    import math

    cos = math.cos(math.radians((_PROJ["lat0"] + _PROJ["lat1"]) / 2))

    def px(lon: float, lat: float) -> tuple[float, float]:
        return (
            round((lon - _PROJ["lon0"]) * _PROJ["k"] * cos, 1),
            round((_PROJ["lat1"] - lat) * _PROJ["k"], 1),
        )

    provinces = []
    for feature in json.loads(PROVINCES_GEOJSON.read_text(encoding="utf-8"))["features"]:
        geometry = feature["geometry"]
        polygons = (
            [geometry["coordinates"]] if geometry["type"] == "Polygon" else geometry["coordinates"]
        )
        path = " ".join(
            "M" + " L".join(f"{x},{y}" for x, y in (px(lon, lat) for lon, lat in ring)) + " Z"
            for polygon in polygons
            for ring in polygon
        )
        provinces.append({"code": feature["properties"]["code"], "d": path})
    width, height = px(_PROJ["lon1"], _PROJ["lat0"])

    located, by_province = [], {}
    for i in incidents:
        deaths = i.get("fatalities_current") or 0
        if i.get("latitude") is not None and i.get("longitude") is not None:
            x, y = px(i["longitude"], i["latitude"])
            located.append(
                {
                    "x": x,
                    "y": y,
                    "r": round(6 + (deaths or 1) ** 0.5 * 2.4, 1),
                    "id": i["public_incident_id"],
                }
            )
        elif i.get("province_code") in centroids:
            by_province.setdefault(i["province_code"], []).append(i)
    province_marks = []
    for code, records in sorted(by_province.items()):
        c = centroids[code]
        x, y = px(float(c["longitude"]), float(c["latitude"]))
        deaths = sum(i.get("fatalities_current") or 0 for i in records)
        province_marks.append(
            {
                "x": x,
                "y": y,
                "r": round(6 + max(deaths, 1) ** 0.5 * 2.4, 1),
                "code": code,
                "label": c["label_tr"],
                "deaths": deaths,
                "ids": [i["public_incident_id"] for i in records],
            }
        )
    site_marks = []
    for site in sites or []:
        if site.get("latitude") is None or site.get("longitude") is None:
            continue
        x, y = px(float(site["longitude"]), float(site["latitude"]))
        site_marks.append({"x": x, "y": y, "ref": site["ref"]})
    return {
        "W": width,
        "H": height,
        "provinces": provinces,
        "markers": located,
        "provinceMarks": province_marks,
        "siteMarks": site_marks,
    }


def _provinces_geo() -> list[dict[str, object]]:
    """Decimated lat/lon province rings for the Leaflet choropleth layer.

    Same Natural Earth source as the vector map; every 2nd vertex at 2
    decimals is ample for a fill layer at country zoom. Display geometry
    only, never evidence."""
    from mining_accidents.geo import PROVINCES_GEOJSON

    provinces = []
    for feature in json.loads(PROVINCES_GEOJSON.read_text(encoding="utf-8"))["features"]:
        geometry = feature["geometry"]
        polygons = (
            [geometry["coordinates"]] if geometry["type"] == "Polygon" else geometry["coordinates"]
        )
        rings = []
        for polygon in polygons:
            ring = polygon[0]
            decimated = ring[::2] if len(ring) > 60 else ring
            rings.append([[round(lat, 2), round(lon, 2)] for lon, lat in decimated])
        provinces.append({"code": feature["properties"]["code"], "rings": rings})
    return provinces


def _pipeline_status(conn: sqlite3.Connection) -> dict[str, int]:
    def count(sql: str) -> int:
        return int(conn.execute(sql).fetchone()[0])

    return {
        "published_incidents": count(
            "SELECT COUNT(*) FROM incidents WHERE publication_status IN "
            "('publishable', 'published')"
        ),
        "records_in_review": count(
            "SELECT COUNT(*) FROM incidents WHERE publication_status NOT IN "
            "('publishable', 'published', 'withdrawn')"
        ),
        "claims_awaiting_review": count(
            "SELECT COUNT(*) FROM claims WHERE review_status = 'needs_review'"
        ),
        "withdrawn_records": count(
            "SELECT COUNT(*) FROM incidents WHERE publication_status = 'withdrawn'"
        ),
        "source_documents": count("SELECT COUNT(*) FROM source_documents"),
        "claims_total": count("SELECT COUNT(*) FROM claims"),
        "decisions_total": count("SELECT COUNT(*) FROM claim_decisions"),
    }


def build_payload(
    conn: sqlite3.Connection, public_dir: str | Path = DEFAULT_PUBLIC_DIR
) -> dict[str, object]:
    """The full dashboard payload (shared by data.js and the artifact build)."""
    public_dir = Path(public_dir)
    incidents = json.loads((public_dir / "incidents.json").read_text(encoding="utf-8"))
    manifest = json.loads((public_dir / "export_manifest.json").read_text(encoding="utf-8"))
    provinces = {e.code: e.label_tr for e in vocabularies.load_vocabulary("turkey_admin_areas")}
    for incident in incidents:
        incident["province_name"] = provinces.get(incident.get("province_code") or "", "")

    sites = _sites(public_dir)
    for site in sites:
        site["province_name"] = provinces.get(site.get("province_code") or "", "")
    payload = {
        "incidents": incidents,
        "sites": sites,
        "province_names": provinces,
        "citations": _citations(public_dir),
        "classifications": _classifications(public_dir),
        "aggregates": _aggregates(conn),
        "province_centroids": _province_centroids(),
        "provinces_geo": _provinces_geo(),
        "map_vector": _map_vector(incidents, _province_centroids(), sites),
        "coverage_gap": analysis.coverage_gap(conn),
        "projection": analysis.projection(conn),
        "policy_events": analysis.policy_events(),
        "rate_context": analysis.rate_context(conn),
        "pipeline": _pipeline_status(conn),
        "export_timestamp": manifest["export_timestamp"],
        "schema_version": manifest["db_schema_version"],
    }
    return payload


def build_dashboard_data(
    conn: sqlite3.Connection,
    public_dir: str | Path = DEFAULT_PUBLIC_DIR,
    output_path: str | Path = DEFAULT_OUTPUT,
) -> Path:
    payload = build_payload(conn, public_dir)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        HEADER
        + "window.MINING_DATA = "
        + json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
        + ";\n",
        encoding="utf-8",
    )
    return output_path
